hmailserver/source/Server/IMAP/IMAPCommandSearch.cpp
In contrast to the `SEARCH BODY`, the `SEARCH TEXT` command didn't perform search in HTML bodies of messages . One had to resort to `SEARCH OR SUBJECT "abc" BODY "abc"`.
=> Include HTMLBody into IMAP TEXT search.

hmailserver/installation/hMailServerInnoExtension.iss
Hi there!
Before the MS SQL CE implementation, the setup with silent switch installed no internal database. In order to have the same behaviour of the setup, I've added the 'useinternaldbms' switch.
Starting setup with the switch /useinternaldbms:false will set the radio from default "use internal database" to "use external database" and during a silent install, it leaves the setup without a database management system.
I'd love to see this change in future versions of hmailserver. Thanks for pulling this change.
Have a great day!
-Bruno.
=> Update hMailServerInnoExtension.iss - new switch

hmailserver/source/Server/Common/SQL/MySQLInterface.cpp
Helps users find the libmysql.dll file faster and helps them get it from a trusted, up-to-date source (https://dev.mysql.com) rather than less reliable files attached to old forum posts.
=> Extended libmysql.dll not available error message

hmailserver/source/Server/Common/Application/IniFileSettings.cpp, hmailserver/source/Server/Common/Application/IniFileSettings.h, hmailserver/source/Server/Common/Util/MailerDaemonAddressDeterminer.cpp, hmailserver/source/Server/SMTP/RuleApplier.cpp, hmailserver/source/Server/SMTP/SMTPForwarding.cpp
This change adds the possiblity/ability to DKIM (and DMARC) sign NDR messages forwarded to external-accounts.
Even if RewriteEnvelopeFromWhenForwardingsetting is set NDR messages EnvelopeFrom will not be rewritten to localaccount address but uses mailer-daemon@ instead as EnvelopeFrom address.
**Requirements to DKIM sign NDR messages**
If the mailer-daemon@ domain exists on the server and DKIM is enabled for that domain the NDR message forwarded to external domains will be DKIM (and optionaly DMARC) signed
=> DKIM sign NDR messages (forwarded to external)

hmailserver/source/Server/Common/Scripting/Events.cpp, hmailserver/source/Server/Common/Scripting/ScriptSite.h
This pull request adds some code to request version 5.8 of the JScript engine from Windows for scripts. The main reason I did this is to get access to built-in JSON object parsing, but there are several other useful features (like being able to index through strings!) that you can see here: https://docs.microsoft.com/en-us/archive/blogs/jscript/versioning-language-features-in-jscript (scroll down to "List of features versioned")
I don't think any of the new features in version 5.8 are incompatible with existing scripts, so I have it enabling the new version for everything.
I also fixed a minor bug with the OnExternalAccountDownload event and how it called JScript code when the remote UID had a single quote in it.
=> Set JScript engine version

hmailserver/source/Server/Common/Application/Errors.txt, hmailserver/source/Server/Common/TCPIP/DNSResolver.cpp, hmailserver/source/Server/Common/TCPIP/DNSResolver.h
hMailServer 5.7.x doesn't resolve MX records that contain CNAME record(s)
Prevent A, AAAA and CNAME Lookup for Null MX
Details: https://github.com/hmailserver/hmailserver/issues/371
=>  5.7.x resolve MX records that contains CNAME record

hmailserver/source/Server/Common/Scripting/Events.cpp
AWStats::LogDeliveryFailure was called twice for each failed message, once in either SMTPDeliverer.cpp and/or ExternalDelivery.cpp and then again in Events.cpp
=> 5.6.x & 5.7.x - AWStats::LogDeliveryFailure called 2x for OnDeliveryFailed

hmailserver/source/Server/Common/AntiSpam/SpamTestSPF.cpp, hmailserver/source/Server/SMTP/SPF/SPF.cpp, hmailserver/source/Server/SMTP/SPF/SPF.h
Include HELO/EHLO hostname for the SPF test for macro expansion (%{h})
"v=spf1 exists:_i.%{i}._h.%{h}._o.%{o}._spf.domain.com -all"
All credits for this go to Søren Raagaard Rathje
=> SPF test to include "HELO/EHLO host" used by DNS macros

hmailserver/source/Server/Common/Scripting/Events.cpp, hmailserver/source/Server/SMTP/SMTPDeliverer.cpp
oMessage object was emtpy when called from OnDeliveryFailed in SMTPDeliverer.cpp but the documentation says the oMessage object is available in OnDeliveryFailed Event
https://github.com/hmailserver/hmailserver/issues/239
=> 5.6.x & 5.7.x Update SMTPDeliverer.cpp

hmailserver/source/Server/Common/AntiSpam/SpamProtection.cpp
Increase maxSizeToScanKB to 256MB
This is also the maximum the official spamassassin spamc client accepts.
=> 5.7.0 Update SpamProtection.cpp Increase maxSizeToScanKB

hmailserver/source/Server/Common/Scripting/ScriptObjectContainer.cpp, hmailserver/source/Server/Common/Scripting/ScriptObjectContainer.h, hmailserver/source/Server/Common/Scripting/ScriptServer.cpp, hmailserver/source/Server/Common/Scripting/ScriptServer.h, hmailserver/source/Server/Common/Util/PasswordValidator.cpp
This pull request adds a new `OnClientValidatePassword` event for scripts. The idea is to allow scripts to authenticate users. For example, if you want to validate user passwords against a database or external login provider, you could write a script to handle that event.
The event is called with two parameters (`OnClientValidatePassword(oAccount, sPassword)`): the account that is trying to sign in and the password that's being used. The script can then set Result.Value to:
* 0 - The user was authenticated, let them in.
* 1 - The user was not authenticated, return an "invalid username or password" error.
* 2 - _(default)_ Bypass the script and continue with the normal hMailServer password validation.
Hopefully this makes some sense, let me know if you have any feedback!
(also, is there …
=> Add OnClientValidatePassword event

hmailserver/source/Server/SMTP/SPF/RMSPF.cpp
The current version of RMSPF.cpp allows for an arbitrary number of digits to be read into the SPF macro segment count; as a result, an SPF record with a macro such as %{d2147483648} would lead to integer overflow in the `num` variable. While this does not lead to any unexpected or dangerous behavior in the current version of the source, an added check would make sure that no future errors come up because of the overflow.
As well (just in case it's needed), I give full permission to license the modifications I've made to the source code under whatever license you use, with or without any attribution.
=> Added integer overflow check for SPF macro segment count

hmailserver/source/Server/Common/Application/IniFileSettings.cpp, hmailserver/source/Server/Common/Application/IniFileSettings.h, hmailserver/source/Server/Common/TCPIP/DNSResolverWinApi.cpp
_Boolean_ **UseDNSCache** (not mine, but something Søren Raagaard Rathje created to bypass use of systems dnscache)
_String_ **DNSServer**
I have a local BIND9 caching en forwarding server, unfortunately Hmailserver by default uses system's default DNS 
This setting can be used to supply a single (local) ip4 IP-Address to force Hmailserver to use that DNS server without having to change system default DNS settings
Eg: in my case both hmailserver as spamassassin are configured to use the same local (ubuntu VM) Bind9 DNS caching en forwarding server instance, this way repeating lookups are cached and forwarding rules are shared, there are a few DNSBL's that require this.
```
/* Disable forwarding for DNSBL queries */
zone "multi.uribl.com" { type forward; forward first; forwarders {}; }; …
```
=> 5.7.0-DNSServer INI Setting(s)

hmailserver/source/Server/ExternalFetcher/POP3ClientConnection.cpp, hmailserver/source/Server/SMTP/SMTPConnection.cpp
5.7 always included the X-hMailServer-Reason-Score: 0 header for any incoming/outgoing message.
To restore compatibility with 5.6 and scripts this fix only includes those headers when X-hMailServer-Spam: YES
=> 5.7.0 Restore X-hMailServer-Reason-Score 5.6.x behaviour

hmailserver/source/Server/Common/AntiSpam/SpamTestHeloHost.cpp
IPv6 fix for HELO check
Valid HELOs are according to RFC2821 4.1.1.1:
```
some.domain.name
[<ipv4-address>]
[IPv6:<ipv6-address>]
```
=> SpamTestHeloHost IPv6 Fix

hmailserver/source/Server/Common/AntiSpam/SpamTestSPF.cpp
SPF Explanation is almost never returned, and I got somewhat irritated/annoyed by the 'empty' parentheses in the error message
=> 5.7.0 Update SPF Error Message

hmailserver/source/Server/SMTP/SMTPConnection.cpp
SMTPConnection::SendBanner_() fixes, check if ends with " ESMTP" and if not append it
=> Automatically append ESMTP to Welcome-message if user has not specified it

hmailserver/source/Server/SMTP/SMTPConnection.cpp
AUTH PLAIN followed by base64 encoded username and password (on same line) in log exposed account password
See:
https://github.com/hmailserver/hmailserver/issues/436
=> Fix: AUTH PLAIN followed by base64 encoded username and password (on same line) in log exposed account password

hmailserver/source/Server/IMAP/IMAPCommandCapability.cpp, hmailserver/source/Server/POP3/POP3Connection.cpp, hmailserver/source/Server/SMTP/SMTPConnection.cpp
**hMailServer: 5.6.8 B2501 (SMTP+POP3), 5.7 (SMTP+POP3+IMAP)**
**Problem:**
Problem was already discussed in #63 marked as solved but still present. If you enable "STARTTLS (Required)" for SMTP/POP3/IMAP connections it'll be detected as 'Unencrypted Cleartext Login' vulnerability because hmailserver will return AUTH/USER/LOGIN as possible capability even if it is not possible to use login before TLS connection is established.
**Solution:**
Don't send AUTH/USER/LOGIN in capabilities list before TLS connection is established if TLS is required.
**Note:**
IMAP is affected if "SASL Plain" is enabled. SMTP and POP3 are affected in default configuration.
=> Fix 'Unencrypted Cleartext Login' vulnerability detection

hmailserver/source/Server/ExternalFetcher/POP3ClientConnection.cpp, hmailserver/source/Server/ExternalFetcher/POP3ClientConnection.h
**use AppendHeader(s) in favor of PrependHeader(s)**
With PrependHeader(s) the X-hMailServer-ExternalAccount header was placed directly above the 1st Received: header, and thus placed completely different relative to other possible added X-hMailServer-* headers
Using AppendHeader(s) the X-hMailServer-ExternalAccount header is placed directly under the last existing header grouping it nicely together with other X-hMailServer-* headers, like:
```
X-hMailServer-ExternalAccount: user@account.name
X-hMailServer-Reason-1: The host name specified in HELO does not match IP address. - (Score: 1)
X-hMailServer-Reason-Score: 1
```
=> Insert X-hMailServer-ExternalAccount-header in same position as other x-hMailServer fields

hmailserver/source/Server/Common/AntiSpam/SpamTestSpamAssassin.cpp
Delete existing Return-Path header(s) before adding our own Return-Path as topmost header to help SpamAssassin with its SPF checks.
=> 5.7.0-SA Return-Path Fixes

hmailserver/source/Server/COM/InterfaceDistributionList.cpp, hmailserver/source/Server/Common/BO/DistributionList.h, hmailserver/source/Server/SMTP/RecipientParser.cpp, hmailserver/source/Tools/Administrator/Main panes/ucDistributionList.Designer.cs, hmailserver/source/Tools/Administrator/Main panes/ucDistributionList.cs, hmailserver/source/WebAdmin/hm_distributionlist.php
Today a had to setup a distribution list for a client, and they asked if it was possible to allow anyone in their domain to send to the list (not being all members)
So i browsed through the code and noticed there are a few more distribution list modes listed in hMailServer.idl RecipientParser.cpp however doesn't contain those additional distribution list modes, the way i see it the mode listed as DomainMembers distribution list mode would fit this clients needs.
=> 5.7.0 DomainMembers DistributionList mode

hmailserver/source/Server/Common/Scripting/ScriptServer.cpp, hmailserver/source/Server/Common/Scripting/ScriptServer.h, hmailserver/source/Server/SMTP/SMTPConnection.cpp
Experimental events OnRecipientUnknown(oClient, oMessage) and OnTooManyInvalidCommands(oClient, oMessage)
Can be usefull to monitor/block repeating offenders, I myself use this to invoke Søren's IDS script and add to the counter.
=> Add events OnRecipientUnknown and OnTooManyInvalidCommands

hmailserver/source/Server/IMAP/IMAPCommandAuthenticate.cpp
RFC4616 describe the deliminator to be NUL not TAB
From chapter 2, ref https://tools.ietf.org/search/rfc4616:
"The authorization identity (authzid), authentication identity
(authcid), password (passwd), and NUL character deliminators SHALL be
transferred as [UTF-8] encoded strings of [Unicode] characters. As
the NUL (U+0000) character is used as a deliminator, the NUL (U+0000)
character MUST NOT appear in authzid, authcid, or passwd productions"
Test server with GSASL: http://ftp.gnu.org/gnu/gsasl/
Did not understand what happened before I saw the code, see forum thread
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=37063
=> SASL deliminator from \t to \0 ref RFC4616

hmailserver/source/Server/IMAP/IMAPCommandAuthenticate.cpp
Reverts hmailserver/hmailserver#385
Indications that this merge causes memory consumption issues.
=> Revert "SASL deliminator from \t to \0 ref RFC4616"

hmailserver/source/Server/Common/TCPIP/DNSResolver.cpp, hmailserver/source/Server/Common/TCPIP/DNSResolver.h
- Fix CNAME (domain) record, see: https://github.com/hmailserver/hmailserver/issues/462 
- Fix IP Address as MX, see: https://github.com/hmailserver/hmailserver/issues/462#issuecomment-1563173781 
- Enhancement Null MX
@martinknafve 
I created 3 (temporary) test in RegressionTests -> Infrastructure -> DnsResolution, which all pass
```
[Test]
public void NullMXRecordShouldNotResolve()
{
// If a MX record contains a Null MX no mail server should be returned
var actualServer = _utilities.GetMailServer("test@allelassers.nl");
Assert.AreEqual("", actualServer);
}
[Test]
public void IPAddressAsMXRecordShouldResolve()
{
// Okay, this is an invalid MX record. The MX record should always contain 
// a host name but in this case it appears an IP address. We'll be kind to
// the domain owner and …
```
=> DNS resolver fixes

hmailserver/source/Server/Common/AntiSpam/DKIM/Canonicalization.cpp
If a subject (or any other header for that matter) value is empty, eg: the header exist but it had no value DKIM verification failed
https://github.com/hmailserver/hmailserver/issues/245
=> Fix: DKIM verification fails when an email is recieved with no subject from Gmail, #245

hmailserver/source/Server/Common/AntiSpam/DKIM/DKIM.cpp
CSA-compliance requires 2 additional headers to be included into the DKIM header tag list: X-CSA-Complaints & List-Unsubscribe-Post
https://certified-senders.org/wp-content/uploads/2019/10/CSA-Compliant-Mail-Headers_Update.pdf
=> Include List-Unsubscribe-Post and X-CSA-Complaints in DKIM signing, #465

hmailserver/source/Server/SMTP/LocalDelivery.cpp
https://github.com/hmailserver/hmailserver/issues/476
File size needs to be updated after Return-Path and optionally Delivered-To header(s) are added
=> hMailServer reports incorrect RFC822.SIZE
